Dumbmake:
	gcc -o Dumbmake TestDumbExample.c DumbExample.c unity/src/unity.c

.PHONY: test
test:
	gcc -o test/test TestDumbExample.c DumbExample.c unity/src/unity.c

main:
	gcc -o src/main DumbExample.c main.c

test1: TestDumbExample.c DumbExample.c unity/src/unity.c
	gcc TestDumbExample.c DumbExample.c unity/src/unity.c -o test1
	
